services:
  app:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    environment:
      DB_HOST: pgbouncer
      DB_NAME: ${POSTGRES_DB:-datastore}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_PORT: ${PGBOUNCER_PORT:-6432}
    ports:
      - "8000:8000"
    depends_on:
      - pgbouncer
    networks:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-datastore}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      ADMIN_USERS: ${POSTGRES_USER:-postgres}
      LISTEN_PORT: ${PGBOUNCER_PORT:-6432}
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
    ports:
      - "${PGBOUNCER_PORT:-6432}:${PGBOUNCER_PORT:-6432}"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
