[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tartarus-lib"
version = "0.1.0"
description = "Python client library for Tartarus Config Store"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Qreater", email = "qreater@gmail.com" }]
dependencies = ["requests>=2.0"]
requires-python = ">=3.9"

keywords = ["config store", "Tartarus", "Python client"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
