name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Run pre-commit
        run: |
          cd backend
          pip install pre-commit
          pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest
    needs: style

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Set up Poetry, Install dependencies, and Run unit tests
        run: |
          cd backend
          pip install poetry
          poetry install
          poetry run pytest tests/unit_tests/ --disable-warnings
  
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    services:
      postgres:
        image: postgres:15.8-alpine3.19
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Set up Poetry, Install dependencies, and Run integration tests
        run: |
          cd backend
          pip install poetry
          poetry install
          poetry run pytest tests/integration_tests/ --disable-warnings
